version: "3"
services:
  hippo:
    image: maheshacharya/myhippoproject-docker-deployment-demo
    networks:
      - net
    ports:
      - 8080
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 2
      update_config:
        delay: 2s
      labels:
        - "com.docker.lb.sticky_session_cookie=JSESSIONID"
        - "traefik.docker.network=hippo_net"
        - "traefik.port=8080"
        - "traefik.frontend.rule=PathPrefix:/"
        - "traefik.backend.loadbalancer.stickiness=true"
  loadbalancer:
    image: traefik
    command: --docker \
      --docker.swarmmode \
      --docker.watch \
      --web \
      --loglevel=DEBUG
    ports:
      - 8080:80
      - 9090:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      update_config:
        delay: 2s
      placement:
         constraints: [node.role == manager]
    networks:
      - net
networks:
  net:
