version: '2'
services:
  hippo-mysql-database:
    image: mysql:5.6.36
    environment:
      - MYSQL_ROOT_PASSWORD=hippo
      - MYSQL_DATABASE=hippo
      - MYSQL_PASSWORD=hippo
      - MYSQL_USER=hippo
      - ON_CREATE_DB="hippo"
    command: mysqld --max_allowed_packet=90M
    volumes:
      - "./hippo/mysql:/var/lib/mysql" 
  apache:
    image: rgoyard/apache-proxy
    ports:
      - '80:80'
      - '443:443'
    expose:
      - "80"
      - "443"
    volumes:
      - "./apache2/sites-available/:/etc/apache2/sites-available/"
    links:
      - hippo1:hippo1
      - hippo2:hippo2
      - hippo2:hippo3    
  hippo1:
    image: maheshacharya/myhippoproject-docker-deployment-demo-mysql
    links:
      - hippo-mysql-database:hippo-mysql-database
  hippo2:
    image: maheshacharya/myhippoproject-docker-deployment-demo-mysql 
    links:
      - hippo-mysql-database:hippo-mysql-database
  hippo3:
    image: maheshacharya/myhippoproject-docker-deployment-demo-mysql
    links:
      - hippo-mysql-database:hippo-mysql-database