apiVersion: v1
kind: ConfigMap
metadata:
  name: hippo-conf
data:
  hippo.conf: |
    server {

      listen       80;
      server_name "cms.cloud-hub.co";

      location / {
        # Set headers for proxy header rewriting, like ProxyPassReverse in Apache http
        # See http://wiki.nginx.org/LikeApache
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://localhost:8080/cms/;
        proxy_redirect default;
        proxy_cookie_path ~*^/.* /;

      }

      location /site/ {
        proxy_set_header Host $host;
        proxy_pass http://localhost:8080/site/;
      }

    }

    server {

      listen       80;
      server_name "hippo.cloud-hub.co";

      location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://localhost:8080/site/;
        proxy_redirect default;
        proxy_cookie_path ~*^/.* /;
      }

    }

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hippo
  labels:
    app: hippo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hippo
    spec:
      volumes:
      - name: hippo-conf
        configMap:
          name: hippo-conf
          items:
          - key: hippo.conf
            path: default
      - name: log
        emptyDir: {}
      containers:
      - name: hippo
        image: maheshacharya/myhippoproject-docker-deployment-demo-mysql
        ports:
        - containerPort: 8080
      - name: nginx
        image: maheshacharya/nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/sites-available/ 
          readOnly: true
          name: hippo-conf
        - mountPath: /var/log/nginx
          name: log
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-vol
        emptyDir: {}
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:5.6
        env: 
        - 
          name: MYSQL_USER
          value: hippo
        - 
          name: MYSQL_PASSWORD
          value: hippo
        - 
          name: MYSQL_DATABASE
          value: hippo
        - 
          name: MYSQL_ROOT_PASSWORD
          value: hippo
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-vol
          mountPath: /var/lib/mysql      
---
apiVersion: v1
kind: Service
metadata:
  name: hippo
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: hippo
---
apiVersion: v1
kind: Service
metadata:
  name: hippo-mysql-database
  labels:
    app: hippo-mysql-database
spec:
  ports:
    - port: 3306
  selector:
    app: mysql


