
#Create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: hippo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hippo
  namespace: hippo
spec:
  replicas: 1
  template:
    metadata:
        labels:
          app: hippo
    spec:
      containers:
      - image: maheshacharya/myhippoproject-docker-deployment-demo
        name: hippo
        ports:
        - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hippo
  namespace: hippo
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: hippo  
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-hippo
  namespace: hippo
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1" 
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: <server name>
    http:
      paths:
      - backend:
          serviceName: hippo
          servicePort: 8080
        path: /
